#!/usr/local/bin/zsh

GIT_SHA=$(git rev-parse --short HEAD)
B=../bin
D=../dist

R=${1}
[[ -z ${R} ]] && R=${GIT_SHA}

[[ -d ${B}/${R} ]] && rm -rf ${B}/${R}
mkdir -p ${B}/${R}
[[ -d ${D}/${R} ]] && rm -rf ${D}/${R}
mkdir -p ${D}/${R}

LDFLAGS="-X main.BuildVersion=${R} -X main.BuildDate=`date -u '+%Y%m%d'` -X main.GitRev=${GIT_SHA}"

GOOS=linux   GOARCH=arm    GOARM=6 go build -ldflags ${LDFLAGS} -o ${B}/${R}/mbdns-${R}-linux-armv6   mbdns.go
GOOS=linux   GOARCH=arm    GOARM=7 go build -ldflags ${LDFLAGS} -o ${B}/${R}/mbdns-${R}-linux-armv7   mbdns.go
GOOS=linux   GOARCH=mipsle         go build -ldflags ${LDFLAGS} -o ${B}/${R}/mbdns-${R}-linux-mipsle  mbdns.go
GOOS=darwin  GOARCH=amd64          go build -ldflags ${LDFLAGS} -o ${B}/${R}/mbdns-${R}-darwin-amd64  mbdns.go
GOOS=freebsd GOARCH=amd64          go build -ldflags ${LDFLAGS} -o ${B}/${R}/mbdns-${R}-freebsd-amd64 mbdns.go
GOOS=linux   GOARCH=amd64          go build -ldflags ${LDFLAGS} -o ${B}/${R}/mbdns-${R}-linux-amd64   mbdns.go

for i (linux-armv6 linux-armv7 linux-mipsle darwin-amd64 freebsd-amd64 linux-amd64) do
    P=mbdns-${R}-${i}
    mkdir -p ${D}/${R}/${P}
    cp ../doc/mbdns.conf.sample ${D}/${R}/${P}
    cp ../README.md             ${D}/${R}/${P}
    cp ../LICENSE               ${D}/${R}/${P}
    cp ${B}/${R}/${P}           ${D}/${R}/${P}
    tar czf ${D}/${R}/${P}.tar.gz -C ${D}/${R} ${P}
    rm -rf ${D}/${R}/${P}
done